version: '3'


volumes:
  go_crud_app_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./compose/go/Dockerfile
    image: go_crud_app
    container_name: go_crud_app
    platform: linux/x86_64
    ports:
      - 8080:8080

  postgres:
    build:
      context: .
    image: postgres:latest
    container_name: go_crud_app_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: go_crud_app
    ports:
      - 5432:5432
    volumes:
      - go_crud_app_postgres_data:/var/lib/postgresql/data:Z